name: Close PR pipeline

on:
  pull_request:
    types: [closed]

jobs:
  build:
    name: Tear down
    runs-on: ubuntu-latest
    steps:
      - name: On Pull request closed
        run: echo "On Pull request closed"

      - name: REF
        run: echo "${{ github.ref}}"

      - name: head_ref
        run: echo "${{ github.HEAD_REF }}"

      - name: base_ref
        run: echo "${{ github.BASE_REF }}"

  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merge