name: Delete branch pipeline

on:
  delete:

jobs:
  build:
      name: Tear down - Delete
      runs-on: ubuntu-latest
      steps:
        - name: On delete branch
          run: echo "On delete branch"