name: Delete or Close PR

on:
  pull_request:
    types: [closed]
  delete:

jobs:
  build:
    name: Delete or Close PR
    runs-on: ubuntu-latest
    steps:
      - name: On Delete or close PR
        run: echo "On Delete or close PR"
        
      - name: REF
        run: echo "${{ github.ref}}"

      - name: head_ref
        run: echo "${{ github.HEAD_REF }}"

      - name: base_ref
        run: echo "${{ github.BASE_REF }}"  
