name: Merge to main pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    name: Tear down
    runs-on: ubuntu-latest
    steps:
      - name: On Push to main
        run: echo "On Push to main"

      - name: REF
        run: echo "${{ github.ref}}"        

      - name: head_ref
        run: echo "${{ github.HEAD_REF }}"

      - name: head_ref
        run: echo "${{ github.BASE_REF }}"  
