name: Close branch pipeline

on:
  push:
    branches: [main]

jobs:
  build:
      name: Tear down
      runs-on: ubuntu-latest
      steps:
        - name: Close branch pipeline
          run: echo "close branch pipeline"